In [1]:
# The Supervised Machine Learning Process
##########################################  Step 1 Data Wrangling & prerocessing #####################
# Step 1 Part 0 Installing machine learning libraries and data wrangling libraries = Done
# Step 1 Part 1 Importing libraries = Done
# Step 1 part 2 Importing dataset = Done (imported into and sql database and then export into csv)
# Step 1 part 3 Taking care of missing data and duplicates = Done (no missing data or duplicates)
# Step 1 part 4 Encoding categorical data = Done, no need for missing but the dataset is checked!
# Step 1 part 5 Feature selection (creating a matrix of features, and the dependant variable we are predicting = Done, machine learning process expects these two entities)
# Step 1 part 6 Splitting dataset into training and test
# Step 1 part 7 Feature scaling
######################################### S# step 2 Simple Linear regression ##############################
# Step 2 Part 0 
# Step 2 Part 1 
# Step 2 part 2 

######################################### Step 3 Logistic regression #############################

# Step 3 Part 0 
# Step 3 Part 1 
# Step 3 part 2 

######################################### Step 4 K Nearest Neighbors (KNN) ####################### 

# Step 4 Part 0 
# Step 4 Part 1 
# Step 4 part 2 

######################################### Step 5 Support vector machines ######################### 

# Step 5 Part 0 
# Step 5 Part 1 
# Step 5 part 2 

######################################### Step 7 Naive Bayes #################### 

# Step 6 Part 0 
# Step 6 Part 1 
# Step 6 part 2 

######################################### Step 6 Decision Trees ##################################

# Step 7 Part 0 
# Step 7 Part 1 
# Step 7 part 2 

######################################### Step 8 Random Forest classification #################### 
# Step 8 Part 0 
# Step 8 Part 1 
# Step 8 part 2 


######################################### THE END #############################


################# Resources and Datasets ########################

###########https://data.mendeley.com/datasets/6tm2d6sz7p/1 ###### Dataset.csv #### Published: 7 June 2023 (0=legitimate,1=phishing)
#df_Dataset = pd.read_csv('datasets/Dataset.csv')

################# Machine learning resoruces 
# https://www.youtube.com/watch?v=i_LwzRVP7bg&t=2687s

In [2]:
# Step 1 Part 0 Installing machine learning libraries and data wrangling libraries = Done

import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install matplotlib
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: matplotlib in /opt/homebrew/anaconda3/lib/python3.11/site-packages (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: numpy in /opt/homebrew/anaconda3/lib/python3.11/site-packages (1.24.3)
Requirement already satisfied: scikit-learn in /opt/homebrew/anaconda3/lib/python3.11/site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.5.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.11.1)
Requirement already satisfied: joblib>=1.1.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from scikit-learn) (2.2.0)

In [3]:
# Step 1 Part 1 Importing libraries = Done

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
# Step 1 part 2 Importing dataset, creating a matrix of features, and the dependant variable we are predicting = Done, machine learning process expects these two entities

#https://data.mendeley.com/datasets/n96ncsr5g4/1 ####16 November 2021 #(0=legitimate,1=phishing)
sql_file_path = 'datasets/index.sql'
#read the index.csv file and convert it into a data frame    
df_phishing_csv = pd.read_csv('datasets/index.csv')

In [5]:
# Step 1 part 2 
df_phishing_csv

,rec_id,url,website,result,created_date
0,1,http://intego3.info/EXEL/index.php,1613573972338075.html,1,2021-02-17 20:29:32
1,2,https://www.mathopenref.com/segment.html,1635698138155948.html,0,2021-10-31 16:35:38
2,3,https://www.computerhope.com/issues/ch000254.htm,1635699228889266.html,0,2021-10-31 16:53:48
3,4,https://www.investopedia.com/terms/n/next-elev...,1635750062162701.html,0,2021-11-01 12:31:02
4,5,https://jobs.emss.org.uk/lcc.aspx,161356510250721.html,0,2021-02-17 18:01:42
...,...,...,...,...,...
79995,79996,https://bestjobmanage.com/adminservicedesk/True/,1622125898152592.html,1,2021-05-27 14:31:38
79996,79997,http://vieuxshack.com/download/adobe/b51f18074...,160822961118687.html,1,2020-12-17 23:56:51
79997,79998,https://www.tumblr.com/search/gas%20mask%20tattoo,163570726902772.html,0,2021-10-31 19:07:49
79998,79999,https://www.magnetic-shield.com/pdf/wc_4.pdf,1635701992217159.html,0,2021-10-31 17:39:52
79999,80000,https://sqm50.codesandbox.io/,1613575077067764.html,1,2021-02-17 20:47:57

In [6]:
# Step 1 part 2 #describe dataset
df_phishing_csv.describe()

             rec_id        result
count  80000.000000  80000.000000
mean   40000.500000      0.375000
std    23094.155105      0.484126
min        1.000000      0.000000
25%    20000.750000      0.000000
50%    40000.500000      0.000000
75%    60000.250000      1.000000
max    80000.000000      1.000000

In [7]:
# Step 1 part 2 #number of records and features (80000 records with 5 columns)
df_phishing_csv.shape

(80000, 5)

In [8]:
# Step 1 part 2 #information about columns and data types
df_phishing_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rec_id        80000 non-null  int64
 1   url           80000 non-null  object
 2   website       80000 non-null  object
 3   result        80000 non-null  int64
 4   created_date  80000 non-null  object
dtypes: int64(2), object(3)
memory usage: 3.1+ MB

In [9]:
# Step 1 part 3 Taking care of missing data
# Check for missing values
print(df_phishing_csv.isnull().sum())

rec_id          0
url             0
website         0
result          0
created_date    0
dtype: int64

In [10]:
# Step 1 part 3 Taking care of missing data
print(df_phishing_csv.isnull().sum())
#checking for unique records on each column
print(df_phishing_csv['website'].nunique())

rec_id          0
url             0
website         0
result          0
created_date    0
dtype: int64
80000

In [11]:
#Step 1 part 4 Encoding categorical data, i.e show any unique values in the column "result"

print(df_phishing_csv['result'].nunique())

2

In [12]:
# Step 1 part 4 #distribution of categorical data in column result,

print(df_phishing_csv['result'].value_counts())

result
0    50000
1    30000
Name: count, dtype: int64

In [13]:
# Step 1 part 3 Taking care of missing data
print(df_phishing_csv.isnull().sum())
#checking for unique records on each column
print(df_phishing_csv['website'].nunique())

rec_id          0
url             0
website         0
result          0
created_date    0
dtype: int64
80000

In [14]:
# Step 1 part 4 #distribution of categorical data in column result,
print(df_phishing_csv['website'].nunique())
print(df_phishing_csv['url'].nunique())

80000
79848

In [15]:
# Step 1 part 4 Encoding categorical data 
#distribution of categorical data in column result, it is difficult for the ML to compute the correlations with strings in the dataset
#Column result has already 1 & 0 therefore there is no need to encode the data into categorical values
print(df_phishing_csv['result'].value_counts())

result
0    50000
1    30000
Name: count, dtype: int64

In [16]:
# Step 1 part 5 Feature selection (creating a matrix of features from the dataset)

X = df_phishing_csv.iloc[:, :-2].values #get all values of the dataset excluding the last two columns(result and Created date) independant variable (features)
y = df_phishing_csv.iloc[:, -2].values #get all pridictive values (result column only) Dependant variable which is the result column

In [23]:
# Step 1 part 6 (Option 1) Splitting dataset into training and test

# valid dataset i.e used to ensure that the model can  handle unseen data after training
# training dataset i.e used to train the model
# test dataset i.e use to test the model

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2,random_state=1)

In [ ]:
# Step 1 part 6 (Option 2) Splitting dataset into training and test
# training: 0-60%
# validation :60-80%
# test: 80-100%

train, valid, test = np.split(df_phishing_csv.sample(frac=1), [int(0.6*len(df_phishing_csv)), int(0.8*len(df_phishing_csv))])

In [ ]:
Alternative test and pliting

def scale_dataset(dataframe, oversample=False):
  X = dataframe[dataframe.columns[:-1]].values
  y = dataframe[dataframe.columns[-1]].values

  scaler = StandardScaler()
  X = scaler.fit_transform(X)

  if oversample:
    ros = RandomOverSampler()
    X, y = ros.fit_resample(X, y)

  data = np.hstack((X, np.reshape(y, (-1, 1))))

  return data, X, y

In [18]:
# Step 1 part 6a X training data set
X_train

array([[72813,
        'https://7a4298b9.sso-mail-secure234ds23d23wd1.pages.dev/?user=rvkt@locaweb.com.br',
        '10000903.html'],
       [20653,
        'http://joinn81.chttwhasappsindbkp5.duckdns.org/login.php',
        '1622777534215369.html'],
       [17357, 'https://payee-safeguard-auth.com/halifax/Login.php',
        '1607006955682801.html'],
       ...,
       [50058,
        'http://papumdg.com.br/proteger/kompte/paypal.fr/0c3609784785b04917ec92f86627c832/erreur.htm?cmd=_error_login-run&amp;amp',
        '1613572945619201.html'],
       [5193,
        'https://www.nchannel.com/blog/considering-shopify-facebook-store-read-first/',
        '1617353616623495.html'],
       [77709, 'https://en.wikipedia.org/wiki/The_Bodyguard_(1992_film)',
        '1635699513056219.html']], dtype=object)

In [19]:
# # Step 1 part 6b X test set dataset
X_test

array([[7127,
        'https://www.experts-exchange.com/questions/24105723/Active-Directory-Authentication-Ports-to-Allow.html',
        '1635698590988337.html'],
       [46625,
        'https://errorbill-updateacc.com/banks/online.citi.eu/Login.php?sslchannel=true&sessionid=uKSb8yC7QwXPW2AF0EZkcNjZeafuSYNti90gxqLqqu7FEtV9dE4KX4SvENHfTeFVUOsINApxEcf22h6iFfUFaFCvj0i4tKh1ojOyWZJFxFl6skqz3vN5EsEYluL5bDnqH3',
        '1607709736870772.html'],
       [67021, 'https://www.jomrun.com/event/sang-jaru-musical-run',
        '1613583851534744.html'],
       ...,
       [40455,
        'https://coinly.cz/mkbbssl/e26e1338b5ad1a29cbfda996b8279552/',
        '1608908000621964.html'],
       [43071, 'https://www.sprinklr.com/', '1613584045779884.html'],
       [13410,
        'https://thecloneworld.in/service-n26-banque/n26_fr-m3tri-withcurlnoantibots/n26_fr-m3tri/Error.php?hash=NzMxODgxNTg4MjMxNw==&token=TW96aWxsYS81LjAgKGlQaG9uZTsgQ1BVIGlQaG9uZSBPUyAxM180IGxpa2UgTWFjIE9TIFgpIEFwcGxlV2ViS2l0LzYwNS4xLjE1IChLSFRNTCwgbGlrZSBHZWNrbykgVmVyc2lvbi8xMy4xIE1vYmlsZS8xNUUxNDggU2FmYXJpLzYwNC4xMTE2LjIwMi4xNC4yNDEyMDIxOkp1bDpUdWU=',
        '1625556645139732.html']], dtype=object)

In [20]:
# # Step 1 part 6c y train set
y_train

array([1, 1, 1, ..., 1, 0, 0])

In [21]:
# # Step 1 part 6d y test set
y_test

array([0, 1, 0, ..., 1, 0, 1])

In [22]:
# Step 1 part 7 Feature scaling ( prevent one feature to dominate the other), get the mean and the sd of your feature