In [34]:
# The Supervised Machine Learning Process (Classification algorithms)
##########################################  Step 1 Data Wrangling & prerocessing #####################
# Step 1 Part 0 Installing machine learning libraries and data wrangling libraries = Done
# Step 1 Part 1 Importing libraries = Done
# Step 1 part 2 Importing dataset = Done (imported into and sql database and then export into csv)
# Step 1 part 3 Taking care of missing data and duplicates = Done (no missing data or duplicates)
# Step 1 part 4 Encoding categorical data = Done, no need for missing but the dataset is checked!
# Step 1 part 5 Feature selection (creating a matrix of features, and the dependant variable we are predicting = Done, machine learning process expects these two entities)
# Step 1 part 6 Splitting dataset into training and test
# Step 1 part 7 Feature scaling

######################################### Step 3 Neural Network #############################

# Step 3 Part 0
# Step 3 Part 1
# Step 3 part 2
######################################### THE END #############################


################# Resources and Datasets ########################

###########https://data.mendeley.com/datasets/6tm2d6sz7p/1 ###### Dataset.csv #### Published: 7 June 2023 (0=legitimate,1=phishing)
#1. df_Dataset = pd.read_csv('datasets/Dataset.csv')

#2. df_phishing_csv = pd.read_csv('datasets/phishing_dataset.csv', on_bad_lines='skip')# https://gregavrbancic.github.io/Phishing-Dataset/# 2020 dataset

################# Machine learning resoruces
# https://www.youtube.com/watch?v=i_LwzRVP7bg&t=2687s

In [35]:
# Step 1 Part 0 Installing machine learning libraries and data wrangling libraries = Done

import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install matplotlib
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install scikit-learn
!{sys.executable} -m pip install tensorflow

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.50.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.25.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.25.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.4.0)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.25.2)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (24.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.10.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.36.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.62.1)
Requirement already satisfied: tensorboard<2.16,>=2.15 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.15.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.43.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.27.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (1.2.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.0.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow) (2.1.5)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (3.2.2)

In [36]:
# Step 1 Part 1 Importing libraries = Done

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [37]:
# Step 1 part 2 Importing dataset, creating a matrix of features, and the dependant variable we are predicting = Done, machine learning process expects these two entities
#df_phishing_csv = pd.read_csv('datasets/phishing_dataset.csv', on_bad_lines='skip')# https://gregavrbancic.github.io/Phishing-Dataset/# 2020 dataset

df_phishing_csv = pd.read_csv('Dataset.csv', on_bad_lines='skip') # https://data.mendeley.com/datasets/6tm2d6sz7p/1 #2023 dataset with 0=legitimate, 1 = phishing

In [38]:
has_nan = df_phishing_csv.isnull().values.any()
has_nan

False

In [39]:
cleaned_df = df_phishing_csv.dropna(how='any')
cleaned_df

,Type,url_length,number_of_dots_in_url,having_repeated_digits_in_url,number_of_digits_in_url,number_of_special_char_in_url,number_of_hyphens_in_url,number_of_underline_in_url,number_of_slash_in_url,number_of_questionmark_in_url,...,having_digits_in_subdomain,number_of_digits_in_subdomain,having_repeated_digits_in_subdomain,having_path,path_length,having_query,having_fragment,having_anchor,entropy_of_url,entropy_of_domain
0,0,37,2,0,0,8,0,0,5,0,...,0,0,1,0,3,0,0,0,4.010412,2.751629
1,1,70,5,0,0,12,0,0,6,0,...,0,0,1,0,4,0,0,0,4.089470,3.532573
2,0,42,2,0,6,8,0,0,3,1,...,0,0,1,0,1,1,0,0,4.386016,3.344698
3,0,46,2,0,0,7,0,0,4,0,...,0,0,1,0,2,0,0,0,4.221947,3.189898
4,0,51,3,0,0,9,0,0,5,0,...,0,0,1,0,3,0,0,0,4.103538,2.952820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247945,0,42,1,0,0,6,0,0,4,0,...,0,0,1,0,2,0,0,0,3.758289,3.323231
247946,0,42,2,0,0,8,0,0,5,0,...,0,0,1,0,3,0,0,0,3.937093,3.026987
247947,1,33,2,0,0,8,0,0,5,0,...,0,0,1,0,3,0,0,0,3.813207,3.327820
247948,1,83,1,1,19,9,0,0,7,0,...,0,0,1,0,5,0,0,0,4.540173,3.375000
247949,0,34,3,0,0,7,0,0,3,0,...,0,0,1,0,1,0,0,0,4.035274,3.182006

In [40]:
# Step 1 part 2 preview dataset
cleaned_df

,Type,url_length,number_of_dots_in_url,having_repeated_digits_in_url,number_of_digits_in_url,number_of_special_char_in_url,number_of_hyphens_in_url,number_of_underline_in_url,number_of_slash_in_url,number_of_questionmark_in_url,...,having_digits_in_subdomain,number_of_digits_in_subdomain,having_repeated_digits_in_subdomain,having_path,path_length,having_query,having_fragment,having_anchor,entropy_of_url,entropy_of_domain
0,0,37,2,0,0,8,0,0,5,0,...,0,0,1,0,3,0,0,0,4.010412,2.751629
1,1,70,5,0,0,12,0,0,6,0,...,0,0,1,0,4,0,0,0,4.089470,3.532573
2,0,42,2,0,6,8,0,0,3,1,...,0,0,1,0,1,1,0,0,4.386016,3.344698
3,0,46,2,0,0,7,0,0,4,0,...,0,0,1,0,2,0,0,0,4.221947,3.189898
4,0,51,3,0,0,9,0,0,5,0,...,0,0,1,0,3,0,0,0,4.103538,2.952820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247945,0,42,1,0,0,6,0,0,4,0,...,0,0,1,0,2,0,0,0,3.758289,3.323231
247946,0,42,2,0,0,8,0,0,5,0,...,0,0,1,0,3,0,0,0,3.937093,3.026987
247947,1,33,2,0,0,8,0,0,5,0,...,0,0,1,0,3,0,0,0,3.813207,3.327820
247948,1,83,1,1,19,9,0,0,7,0,...,0,0,1,0,5,0,0,0,4.540173,3.375000
247949,0,34,3,0,0,7,0,0,3,0,...,0,0,1,0,1,0,0,0,4.035274,3.182006

In [41]:
# Step 1 part 2 #describe dataset
cleaned_df.describe()

,Type,url_length,number_of_dots_in_url,having_repeated_digits_in_url,number_of_digits_in_url,number_of_special_char_in_url,number_of_hyphens_in_url,number_of_underline_in_url,number_of_slash_in_url,number_of_questionmark_in_url,...,having_digits_in_subdomain,number_of_digits_in_subdomain,having_repeated_digits_in_subdomain,having_path,path_length,having_query,having_fragment,having_anchor,entropy_of_url,entropy_of_domain
count,247950.000000,247950.000000,247950.000000,247950.000000,247950.000000,247950.000000,247950.000000,247950.000000,247950.000000,247950.000000,...,247950.000000,247950.000000,247950.0,247950.0,247950.000000,247950.000000,247950.000000,247950.000000,247950.000000,247950.000000
mean,0.481585,58.358197,2.894075,0.162351,4.366070,10.303218,0.600867,0.204049,4.784533,0.159911,...,0.064529,0.224013,1.0,0.0,2.606977,0.126501,0.002303,0.000944,4.257222,3.389839
std,0.499662,29.764620,1.690970,0.368773,9.579032,4.718381,1.235599,0.653502,1.812574,0.449506,...,0.245694,1.276447,0.0,0.0,1.636938,0.332414,0.047933,0.030706,0.328098,0.376361
min,0.000000,12.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,2.000000,0.000000,...,0.000000,0.000000,1.0,0.0,0.000000,0.000000,0.000000,0.000000,2.648939,1.386274
25%,0.000000,39.000000,2.000000,0.000000,0.000000,7.000000,0.000000,0.000000,4.000000,0.000000,...,0.000000,0.000000,1.0,0.0,2.000000,0.000000,0.000000,0.000000,4.038910,3.180833
50%,0.000000,49.000000,3.000000,0.000000,0.000000,9.000000,0.000000,0.000000,4.000000,0.000000,...,0.000000,0.000000,1.0,0.0,2.000000,0.000000,0.000000,0.000000,4.208298,3.392747
75%,1.000000,69.000000,3.000000,0.000000,4.000000,11.000000,1.000000,0.000000,5.000000,0.000000,...,0.000000,0.000000,1.0,0.0,3.000000,0.000000,0.000000,0.000000,4.428036,3.606937
max,1.000000,191.000000,28.000000,1.000000,144.000000,75.000000,23.000000,47.000000,30.000000,17.000000,...,1.000000,44.000000,1.0,0.0,28.000000,1.000000,1.000000,1.000000,5.866327,4.957323

In [42]:
# Step 1 part 2 #number of records and features (247950 records with 42 features)
cleaned_df.shape

(247950, 42)

In [43]:
# Step 1 part 2 #information about columns and data types
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247950 entries, 0 to 247949
Data columns (total 42 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Type                                       247950 non-null  int64
 1   url_length                                 247950 non-null  int64
 2   number_of_dots_in_url                      247950 non-null  int64
 3   having_repeated_digits_in_url              247950 non-null  int64
 4   number_of_digits_in_url                    247950 non-null  int64
 5   number_of_special_char_in_url              247950 non-null  int64
 6   number_of_hyphens_in_url                   247950 non-null  int64
 7   number_of_underline_in_url                 247950 non-null  int64
 8   number_of_slash_in_url                     247950 non-null  int64
 9   number_of_questionmark_in_url              247950 non-null  int64
 10  number_of_equal_in_url                     247950 non-null  int64
 11  number_of_at_in_url                        247950 non-null  int64
 12  number_of_dollar_in_url                    247950 non-null  int64
 13  number_of_exclamation_in_url               247950 non-null  int64
 14  number_of_hashtag_in_url                   247950 non-null  int64
 15  number_of_percent_in_url                   247950 non-null  int64
 16  domain_length                              247950 non-null  int64
 17  number_of_dots_in_domain                   247950 non-null  int64
 18  number_of_hyphens_in_domain                247950 non-null  int64
 19  having_special_characters_in_domain        247950 non-null  int64
 20  number_of_special_characters_in_domain     247950 non-null  int64
 21  having_digits_in_domain                    247950 non-null  int64
 22  number_of_digits_in_domain                 247950 non-null  int64
 23  having_repeated_digits_in_domain           247950 non-null  int64
 24  number_of_subdomains                       247950 non-null  int64
 25  having_dot_in_subdomain                    247950 non-null  int64
 26  having_hyphen_in_subdomain                 247950 non-null  int64
 27  average_subdomain_length                   247950 non-null  float64
 28  average_number_of_dots_in_subdomain        247950 non-null  int64
 29  average_number_of_hyphens_in_subdomain     247950 non-null  int64
 30  having_special_characters_in_subdomain     247950 non-null  int64
 31  number_of_special_characters_in_subdomain  247950 non-null  int64
 32  having_digits_in_subdomain                 247950 non-null  int64
 33  number_of_digits_in_subdomain              247950 non-null  int64
 34  having_repeated_digits_in_subdomain        247950 non-null  int64
 35  having_path                                247950 non-null  int64
 36  path_length                                247950 non-null  int64
 37  having_query                               247950 non-null  int64
 38  having_fragment                            247950 non-null  int64
 39  having_anchor                              247950 non-null  int64
 40  entropy_of_url                             247950 non-null  float64
 41  entropy_of_domain                          247950 non-null  float64
dtypes: float64(3), int64(39)
memory usage: 79.5 MB

In [44]:
# Step 1 part 3 Taking care of missing data
# Check for missing values
print(cleaned_df.isnull().sum())

Type                                         0
url_length                                   0
number_of_dots_in_url                        0
having_repeated_digits_in_url                0
number_of_digits_in_url                      0
number_of_special_char_in_url                0
number_of_hyphens_in_url                     0
number_of_underline_in_url                   0
number_of_slash_in_url                       0
number_of_questionmark_in_url                0
number_of_equal_in_url                       0
number_of_at_in_url                          0
number_of_dollar_in_url                      0
number_of_exclamation_in_url                 0
number_of_hashtag_in_url                     0
number_of_percent_in_url                     0
domain_length                                0
number_of_dots_in_domain                     0
number_of_hyphens_in_domain                  0
having_special_characters_in_domain          0
number_of_special_characters_in_domain       0
having_digits_in_domain                      0
number_of_digits_in_domain                   0
having_repeated_digits_in_domain             0
number_of_subdomains                         0
having_dot_in_subdomain                      0
having_hyphen_in_subdomain                   0
average_subdomain_length                     0
average_number_of_dots_in_subdomain          0
average_number_of_hyphens_in_subdomain       0
having_special_characters_in_subdomain       0
number_of_special_characters_in_subdomain    0
having_digits_in_subdomain                   0
number_of_digits_in_subdomain                0
having_repeated_digits_in_subdomain          0
having_path                                  0
path_length                                  0
having_query                                 0
having_fragment                              0
having_anchor                                0
entropy_of_url                               0
entropy_of_domain                            0
dtype: int64

In [45]:
# Step 1 part 3a Taking care of missing data
print(cleaned_df.isnull().sum())

Type                                         0
url_length                                   0
number_of_dots_in_url                        0
having_repeated_digits_in_url                0
number_of_digits_in_url                      0
number_of_special_char_in_url                0
number_of_hyphens_in_url                     0
number_of_underline_in_url                   0
number_of_slash_in_url                       0
number_of_questionmark_in_url                0
number_of_equal_in_url                       0
number_of_at_in_url                          0
number_of_dollar_in_url                      0
number_of_exclamation_in_url                 0
number_of_hashtag_in_url                     0
number_of_percent_in_url                     0
domain_length                                0
number_of_dots_in_domain                     0
number_of_hyphens_in_domain                  0
having_special_characters_in_domain          0
number_of_special_characters_in_domain       0
having_digits_in_domain                      0
number_of_digits_in_domain                   0
having_repeated_digits_in_domain             0
number_of_subdomains                         0
having_dot_in_subdomain                      0
having_hyphen_in_subdomain                   0
average_subdomain_length                     0
average_number_of_dots_in_subdomain          0
average_number_of_hyphens_in_subdomain       0
having_special_characters_in_subdomain       0
number_of_special_characters_in_subdomain    0
having_digits_in_subdomain                   0
number_of_digits_in_subdomain                0
having_repeated_digits_in_subdomain          0
having_path                                  0
path_length                                  0
having_query                                 0
having_fragment                              0
having_anchor                                0
entropy_of_url                               0
entropy_of_domain                            0
dtype: int64

In [46]:
# Step 1 part 3b Taking care of missing data
#checking for unique records on each column
print(cleaned_df['Type'].nunique())

2

In [47]:
#Step 1 part 3c Encoding categorical data, i.e show any unique values in the column "result"

print(cleaned_df['Type'].nunique())

2

In [48]:
# Step 1 part 3d #distribution of categorical data in column result,

print(cleaned_df['Type'].value_counts())

Type
0    128541
1    119409
Name: count, dtype: int64

In [49]:
# Step 1 part 3e Taking care of missing data
print(cleaned_df.isnull().sum())

Type                                         0
url_length                                   0
number_of_dots_in_url                        0
having_repeated_digits_in_url                0
number_of_digits_in_url                      0
number_of_special_char_in_url                0
number_of_hyphens_in_url                     0
number_of_underline_in_url                   0
number_of_slash_in_url                       0
number_of_questionmark_in_url                0
number_of_equal_in_url                       0
number_of_at_in_url                          0
number_of_dollar_in_url                      0
number_of_exclamation_in_url                 0
number_of_hashtag_in_url                     0
number_of_percent_in_url                     0
domain_length                                0
number_of_dots_in_domain                     0
number_of_hyphens_in_domain                  0
having_special_characters_in_domain          0
number_of_special_characters_in_domain       0
having_digits_in_domain                      0
number_of_digits_in_domain                   0
having_repeated_digits_in_domain             0
number_of_subdomains                         0
having_dot_in_subdomain                      0
having_hyphen_in_subdomain                   0
average_subdomain_length                     0
average_number_of_dots_in_subdomain          0
average_number_of_hyphens_in_subdomain       0
having_special_characters_in_subdomain       0
number_of_special_characters_in_subdomain    0
having_digits_in_subdomain                   0
number_of_digits_in_subdomain                0
having_repeated_digits_in_subdomain          0
having_path                                  0
path_length                                  0
having_query                                 0
having_fragment                              0
having_anchor                                0
entropy_of_url                               0
entropy_of_domain                            0
dtype: int64

In [50]:
# Step 1 part 3f Taking care of missing data
#checking for unique records on each column
print(cleaned_df['Type'].nunique())

2

In [51]:
# Step 1 part 4 #distribution of categorical data in column result,

In [52]:
# Step 1 part 4 Encoding categorical data
#distribution of categorical data in column Type
#Column Type has already 1 & 0 therefore there is no need to encode the data into categorical values
print(cleaned_df['Type'].value_counts())

Type
0    128541
1    119409
Name: count, dtype: int64

In [53]:
# Step 1 part 5 Feature selection (creating a matrix of features from the dataset)

X = cleaned_df.iloc[:, 1:].values #get all valriable (features) except the first column
y = cleaned_df.iloc[:, 0].values #get all pridictive values from the first column

In [54]:
# Step 1 part 6 (Option 1) Splitting dataset into training and test

# valid dataset i.e used to ensure that the model can  handle unseen data after training
# training dataset i.e used to train the model
# test dataset i.e use to evaluate the model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [55]:
# Step 1 part 7 feature scaling to improve training perfomance
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [56]:
#Building a Neural Network Model Layout
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
NNmodel = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [57]:
#Compile the model

NNmodel.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

In [58]:
# Train the model
NNmodel.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
4959/4959 [==============================] - 28s 5ms/step - loss: 0.3174 - accuracy: 0.8635 - val_loss: 0.2853 - val_accuracy: 0.8796
Epoch 2/10
4959/4959 [==============================] - 12s 3ms/step - loss: 0.2773 - accuracy: 0.8839 - val_loss: 0.2705 - val_accuracy: 0.8872
Epoch 3/10
4959/4959 [==============================] - 12s 2ms/step - loss: 0.2672 - accuracy: 0.8886 - val_loss: 0.2669 - val_accuracy: 0.8891
Epoch 4/10
4959/4959 [==============================] - 20s 4ms/step - loss: 0.2610 - accuracy: 0.8915 - val_loss: 0.2578 - val_accuracy: 0.8927
Epoch 5/10
4959/4959 [==============================] - 13s 3ms/step - loss: 0.2560 - accuracy: 0.8932 - val_loss: 0.2567 - val_accuracy: 0.8929
Epoch 6/10
4959/4959 [==============================] - 11s 2ms/step - loss: 0.2523 - accuracy: 0.8947 - val_loss: 0.2536 - val_accuracy: 0.8946
Epoch 7/10
4959/4959 [==============================] - 12s 2ms/step - loss: 0.2490 - accuracy: 0.8972 - val_loss: 0.2497 - val_accuracy: 0.8982
Epoch 8/10
4959/4959 [==============================] - 12s 2ms/step - loss: 0.2466 - accuracy: 0.8983 - val_loss: 0.2472 - val_accuracy: 0.8991
Epoch 9/10
4959/4959 [==============================] - 11s 2ms/step - loss: 0.2439 - accuracy: 0.8993 - val_loss: 0.2507 - val_accuracy: 0.8960
Epoch 10/10
4959/4959 [==============================] - 12s 2ms/step - loss: 0.2415 - accuracy: 0.9006 - val_loss: 0.2448 - val_accuracy: 0.8990

In [59]:
#Model training
# Evaluate the model on the test set
test_loss, test_accuracy = NNmodel.evaluate(X_test, y_test)
print(f"Accuracy: {test_accuracy}")

1550/1550 [==============================] - 3s 2ms/step - loss: 0.2446 - accuracy: 0.8990
Accuracy: 0.8989514112472534

In [60]:
predict_phishing = NNmodel.predict(X_test)
#convert to binary
binary_predictions = (predict_phishing > 0.5).astype(int)

1550/1550 [==============================] - 3s 2ms/step

In [61]:
# precision
precision = tf.keras.metrics.Precision()
precision.update_state(y_test, binary_predictions)
model_precision = precision.result().numpy()

print(f"Precision: {model_precision}")

Precision: 0.9046064019203186

In [62]:
predict_phishing = NNmodel.predict(X_test)

# Convert probabilities to binary
binary_predictions = (predict_phishing > 0.5).astype(int)

# Calculate recall
recall = tf.keras.metrics.Recall()
recall.update_state(y_test, binary_predictions)
model_recall = recall.result().numpy()

print(f"Recall: {model_recall}")

1550/1550 [==============================] - 2s 1ms/step
Recall: 0.8829425573348999

In [63]:
predict_phishing = NNmodel.predict(X_test)
predictions_tensor = tf.convert_to_tensor(predict_phishing, dtype=tf.float32)
labels_tensor = tf.convert_to_tensor(y_test, dtype=tf.float32)
auc = tf.keras.metrics.AUC(curve='ROC')
auc.update_state(labels_tensor, predictions_tensor)
roc_auc = auc.result().numpy()
print(f"ROC: {roc_auc}")

1550/1550 [==============================] - 2s 1ms/step
ROC: 0.9621325731277466

In [64]:
from sklearn.metrics import confusion_matrix
threshold = 0.5
y_pred = (predict_phishing > threshold).astype(int)
cm = confusion_matrix(y_test, y_pred)
TP = cm[1, 1]  # TP
TN = cm[0, 0]  # TN
FP = cm[0, 1]  # FP
FN = cm[1, 0]  # FN

numerator = (TP * TN) - (FP * FN)
denominator = np.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN))
MCC = numerator / denominator if denominator != 0 else 0

print(f"MCC: {MCC}")

MCC: 0.7976375939289034