In [1]:
import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install matplotlib
!{sys.executable} -m pip install numpy

Requirement already satisfied: pandas in /opt/homebrew/anaconda3/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: matplotlib in /opt/homebrew/anaconda3/lib/python3.11/site-packages (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: numpy in /opt/homebrew/anaconda3/lib/python3.11/site-packages (1.24.3)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
phishing_01= pd.read_csv('MendelayPhishingWebsitesDatasetSept2020.csv')

# source for Dataset.csv https://data.mendeley.com/datasets/6tm2d6sz7p/1
phishing_02= pd.read_csv('Dataset.csv')

# source https://www.mdpi.com/2076-3417/13/24/13269 ""
phishing_03_train= pd.read_csv('phishing_dataset_train.csv')
phishing_02_test= pd.read_csv('phishing_dataset_test.csv')

In [4]:
phishing_02

,Type,url_length,number_of_dots_in_url,having_repeated_digits_in_url,number_of_digits_in_url,number_of_special_char_in_url,number_of_hyphens_in_url,number_of_underline_in_url,number_of_slash_in_url,number_of_questionmark_in_url,...,having_digits_in_subdomain,number_of_digits_in_subdomain,having_repeated_digits_in_subdomain,having_path,path_length,having_query,having_fragment,having_anchor,entropy_of_url,entropy_of_domain
0,0,37,2,0,0,8,0,0,5,0,...,0,0,1,0,3,0,0,0,4.010412,2.751629
1,1,70,5,0,0,12,0,0,6,0,...,0,0,1,0,4,0,0,0,4.089470,3.532573
2,0,42,2,0,6,8,0,0,3,1,...,0,0,1,0,1,1,0,0,4.386016,3.344698
3,0,46,2,0,0,7,0,0,4,0,...,0,0,1,0,2,0,0,0,4.221947,3.189898
4,0,51,3,0,0,9,0,0,5,0,...,0,0,1,0,3,0,0,0,4.103538,2.952820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247945,0,42,1,0,0,6,0,0,4,0,...,0,0,1,0,2,0,0,0,3.758289,3.323231
247946,0,42,2,0,0,8,0,0,5,0,...,0,0,1,0,3,0,0,0,3.937093,3.026987
247947,1,33,2,0,0,8,0,0,5,0,...,0,0,1,0,3,0,0,0,3.813207,3.327820
247948,1,83,1,1,19,9,0,0,7,0,...,0,0,1,0,5,0,0,0,4.540173,3.375000
247949,0,34,3,0,0,7,0,0,3,0,...,0,0,1,0,1,0,0,0,4.035274,3.182006

In [7]:
phishing_03_train

,domain_similarity,url_length,http_protocol,num_dot,num_slash,num_double_slash,num_hyphen,num_underscore,num_equal,num_paranthesis,...,url_inc_at,url_inc_ip,response_history,redirect,num_a_href,num_input,num_button,num_link_href,num_iframe,class
0,0.89,29,1,1,0,1,0,0,0,0,...,0,0,13,0,37,1,13,4,0,0
1,0.88,28,1,1,0,1,0,0,0,0,...,0,0,13,0,45,2,8,11,3,0
2,0.87,35,1,0,0,1,0,0,0,0,...,0,0,25,0,49,1,2,24,0,1
3,0.49,64,1,1,3,1,0,0,0,0,...,0,0,25,0,6,1,1,3,0,1
4,0.83,23,1,1,0,1,0,0,0,0,...,0,0,13,0,20,0,0,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,0.88,27,1,2,0,1,0,0,0,0,...,0,0,13,0,417,25,28,24,1,0
696,0.39,48,0,1,1,1,1,0,0,0,...,0,0,20,1,0,0,0,1,0,1
697,1.00,23,1,0,0,1,0,0,0,0,...,0,0,13,0,51,0,0,4,0,0
698,1.00,18,1,0,0,1,0,0,0,0,...,0,0,13,0,139,1,11,20,2,0
699,0.36,60,1,0,3,1,1,1,0,0,...,0,0,25,0,11,0,0,5,0,1